#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Sep 11 23:45:58 IST 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim test_Risc_16_bit_behav -key {Behavioral:sim_1:Functional:test_Risc_16_bit} -tclbatch test_Risc_16_bit.tcl -log simulate.log"
xsim test_Risc_16_bit_behav -key {Behavioral:sim_1:Functional:test_Risc_16_bit} -tclbatch test_Risc_16_bit.tcl -log simulate.log

